### ISSUE TITLE
City Justice

### ISSUE THREAD

**Issue by tazzaoui** [dpploy/cortix-nb#10]
The second to last cell (commented out) in `run_city_justice.ipynb` returns an error to do with the name not being found as an index.

**Comment by dealmeidavf** [comment]
I saw but no time to fix right now. Does the `run_city_justice.py` run file in the examples run correctly? This block in the run file should do the same thing as the notebook:

https://github.com/dpploy/cortix/blob/a79866921e06236520fe0a647b249d19fd14db11/cortix/examples/city_justice/run_city_justice.py#L163-L171

Anyway I will look at it later.

**Comment by dealmeidavf** [comment]
This is a bug in Cortix:

https://github.com/dpploy/cortix/issues/228
